Last/urls.py
from django.urls import path

from app01.views import admin,order,service,work,hotel,carcer,chart,info

from django.urls import path,re_path
from django.conf import settings
from django.views.static import serve

urlpatterns = [

    #配置上传文件路径
    re_path(r'^media/(?P<path>.*)$',serve,{'document_root':settings.MEDIA_ROOT},name='media'),
    #服务展示
    path('service/list/', service.service_list),
    path('service/add/', service.service_add),
    path('service/<int:id>/edit/', service.service_edit),
    path('service/<int:id>/delete/', service.service_delete),
    path('service/show/',service.service_show),

    # 管理员管理
    path('admin/list/',admin.admin_list),
    path('admin/add/',admin.admin_add),
    path('admin/<int:id>/edit/',admin.admin_edit),
    path('admin/<int:id>/delete/',admin.admin_delete),
    path('admin/<int:id>/reset/',admin.admin_reset),

    #工作人员
    path('work/list/', work.work_list),
    path('work/add/', work.work_add),
    path('work/<int:id>/edit/',work.work_edit),
    path('work/<int:id>/delete/', work.work_delete),


    # 登录管理
    path('login/',admin.login),

    #注销
    path('lagout/',admin.lagout),

    # 订单管理
    path('order/list/',order.order_list),
    path('order/add/',order.order_add),
    path('order/delete/',order.order_delete),
    # path('order/detail/',order.order_detail),
    # path('order/edit/',order.order_edit),

    #酒席管理
    path('hotel/list/',hotel.hotel_list),
    path('hotel/add/',hotel.hotel_add),
    path('hotel/<int:id>/edit/', work.work_edit),
    path('hotel/<int:id>/delete/', work.work_delete),


    #职务管理
    path('carcer/list/',carcer.carcer_list),
    path('carcer/add/',carcer.carcer_add),
    path('carcer/<int:id>/delete/',carcer.carcer_delete),
    path('carcer/<int:id>/edit/',carcer.carcer_edit),

    #图片验证码
    path('image/code/',admin.image_code),


    #数据显示
    path('chart/list/',chart.chart_list),

    #个人信息
    path('info/people/',info.info_list),

    #注册
    path('register/',info.register),








]

app01/models.py
from django.db import models

# Create your models here.
class ServiceCar(models.Model):
    '''婚车表'''
    num=models.IntegerField(verbose_name="数量")
    typeCar=models.CharField(verbose_name="品牌",max_length=32)
    price=models.DecimalField(max_digits=10, decimal_places=2,verbose_name="价格")
    status=(
        (0,"已占用"),
        (1,"待占用")
    )
    status_choice=models.SmallIntegerField(verbose_name="状态",choices=status,default=1)
    colour=models.CharField(verbose_name="颜色",max_length=32)

class Hotel(models.Model):
    '''酒席表'''
    num=models.IntegerField(verbose_name="数量")
    wine=models.CharField(verbose_name="酒种",max_length=64)
    price=models.DecimalField(max_digits=10, decimal_places=2,verbose_name="价格")
    wine_choice=(
        (0,"500"),
        (1,"800"),
        (2,"1000"),
        (3,"1200")
    )
    wine_type=models.SmallIntegerField(verbose_name="类型",choices=wine_choice,default=1)

class Depart(models.Model):
    '''部门表'''

    title = models.CharField(max_length=32, verbose_name="职务名称")

    def __str__(self):
        return self.title

class Work(models.Model):
    '''工作人员录入表'''
    name=models.CharField(max_length=64,verbose_name="姓名")
    choice=(
        (0,"男"),
        (1,"女")
    )
    gender=models.SmallIntegerField(default=0,verbose_name="性别",choices=choice)
    cancer=models.ForeignKey(verbose_name="职务",to=Depart,to_field="id",on_delete=models.CASCADE)
    phone=models.CharField(max_length=64,verbose_name="电话")
    address=models.CharField(verbose_name="地址",max_length=64)
    password=models.CharField(verbose_name="密码",max_length=64)
    #本质上还是CharField，自动保存数据
    photo=models.FileField(verbose_name="照片",max_length=128,upload_to="photo/")

class Admin(models.Model):
    '''管理员管理'''
    adminname=models.CharField(max_length=32,verbose_name="名称")
    password=models.CharField(max_length=32,verbose_name="密码")

class Order(models.Model):
    '''订单管理'''
    name=models.CharField(verbose_name="订单名",max_length=64)
    datatime=models.DateField(verbose_name="婚礼日期")
    phone=models.CharField(verbose_name="联系人电话",max_length=64)
    address=models.CharField(max_length=64,verbose_name="婚礼地址")
    oid=models.CharField(verbose_name="订单号",max_length=64)
    status=(
        (0,"待支付"),
        (1,"已支付")
    )
    status_choice=models.SmallIntegerField(default=0,verbose_name="支付状态",choices=status)
    level=(
        (0,"普通客户"),
        (1,"vip客户")
    )
    level_choice=models.SmallIntegerField(default=0,verbose_name="级别",choices=level)

app01/views/admin.py
from django.shortcuts import render,redirect,HttpResponse
from app01.models import Admin
from app01.utils.bootstraps import Bootstrap
from io import BytesIO
from app01.utils.code import check_code

def admin_list(request):
    queryset=Admin.objects.all()
    return render(request,"admin_list.html",{"queryset":queryset})

class AdminModelForm(Bootstrap):
    class Meta:
        model=Admin
        fields="__all__"

def admin_add(request):
    '''管理员添加'''
    title="添加管理员"
    if request.method=="GET":
        form=AdminModelForm()
        return render(request,"change.html",{"form":form,"title":title})
    else:
        form=AdminModelForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect("/admin/list/")
        return render(request,"change.html",{"form":form})


def admin_delete(request,id):
    '''管理员删除'''
    Admin.objects.filter(id=id).delete()
    return redirect("/admin/list/")

def admin_edit(request,id):
    '''管理员编辑'''
    data=Admin.objects.filter(id=id).first()
    if request.method=="GET":
        form=AdminModelForm(instance=data)
        return render(request,"change.html",{"form":form})
    else:
        form=AdminModelForm(data=request.POST,instance=data)
        if form.is_valid():
            form.save()
            return redirect("/admin/list/")
        else:
            return render(request,"change.html",{"form":form})


class RestModelForm(Bootstrap):
    class Meta:
        model=Admin
        fields=["password"]
def admin_reset(request,id):
    '''重置密码'''
    title="重置密码"
    data=Admin.objects.filter(id=id).first()
    if request.method=="GET":
        form=RestModelForm()
        return render(request,"change.html",{"form":form,"title":title})
    form=RestModelForm(data=request.POST,instance=data)
    if form.is_valid():
        form.save()
        return redirect("/admin/list/")
    return render(request,"change.html",{"form":form})


def lagout(request):
    '''退出'''
    request.session.clear()
    return redirect("/login/")


from django import forms
class LoginForm(forms.Form):

    adminname=forms.CharField(
        label="用户名",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True
    )
    password=forms.CharField(
        label="密码",
        widget=forms.PasswordInput(attrs={"class":"form-control"},render_value=True),
        required=True
    )

    code=forms.CharField(
        label="验证码",
        widget=forms.TextInput(attrs={"class":"form-control"}),
        required=True
    )

def login(request):
    '''登录'''
    if request.method=="GET":
        form=LoginForm()
        return render(request,"login.html",{"form":form})
    form=LoginForm(data=request.POST)
    if form.is_valid():
        user_input_code=form.cleaned_data.pop("code")
        code = request.session.get("image_code","")
        if code.upper()!=user_input_code.upper():
            form.add_error("code","验证码错误")
            return render(request,"login.html",{"form":form})
        admin_object=Admin.objects.filter(**form.cleaned_data).first()
        if not admin_object:
            form.add_error("password","用户或密码错误")
            return render(request,"login.html",{"form":form})
        else:
            request.session["info"]={"id":admin_object.id,"name":admin_object.adminname}
            #7天免登陆
            request.session.set_expiry(60*60*24*7)
            return redirect("/service/show/")
    return render(request,"login.html",{"form":form})

def image_code(request):
    '''生成随机验证码图片'''
    img,code_string=check_code()

    #将用户填写验证码写入到自己的session中(以便后续获取验证码再进行校验)
    request.session['image_code']=code_string
    # 给session设置60s超时
    request.session.set_expiry(60)

    # 将验证码文件写入内存中
    stream=BytesIO()
    img.save(stream,'png')
    # 将图片内容返回给浏览器
    return HttpResponse(stream.getvalue())

app01/views/carcer.py
from django.shortcuts import render,redirect
from django.utils.safestring import mark_safe

from app01.models import Depart


def carcer_list(request):
    '''职务列表'''

    data_dict={}
    search_data=request.GET.get('q',"")
    if search_data:
        data_dict["title__contains"]=search_data

    page = int(request.GET.get("page", "1"))  # 当前页
    page_size = 10  # 每页显示10条数据
    start = (page - 1) * 10
    end = page * 10
    total_count = Depart.objects.filter(**data_dict).order_by("-id").count()  # 数据总条数

    # 计算总页码
    total_page_count, div = divmod(total_count, page_size)
    if div > 1:  # 余数大于1
        total_page_count += 1

    # 分页第二步
    # 计算出,显示当前页的前5页,后5页
    plus = 5

    if total_page_count < 2 * plus + 1:
        # 当数据库的数据库比较少的时候,都没有达到11页
        start_page = 1
        end_page = total_page_count
    else:
        # 当前页小于5时
        if page <= plus:
            start_page = 1
            end_page = 2 * plus + 1
        # 当数据库的数据库比较多的时候
        else:
            # 当前页大于5时
            if page + plus > total_page_count:
                start_page = total_page_count - 2 * plus  # 往前推10个
                end_page = total_page_count
            else:
                start_page = page - plus
                end_page = page + plus + 1

    tpl_str_list = []

    # 首页
    prve = '<li><a href="?page={}">首页</a></li>'.format(1)
    tpl_str_list.append(prve)

    # 上一页
    if page > 1:
        prve = '<li><a href="?page={}">上一页</a></li>'.format(page - 1)
    else:
        prve = '<li><a href="?page={}">上一页</a></li>'.format(1)
    tpl_str_list.append(prve)

    for i in range(start_page, end_page + 1):
        if i == page:
            ele = '<li class="active"><a href="?page={}">{}</a></li>'.format(i, i)
        else:
            ele = '<li><a href="?page={}">{}</a></li>'.format(i, i)
        tpl_str_list.append(ele)

    # 下一页
    if page < total_page_count:
        prve = '<li><a href="?page={}">下一页</a></li>'.format(page + 1)
    else:
        prve = '<li><a href="?page={}">下一页</a></li>'.format(total_page_count)
    tpl_str_list.append(prve)

    # 尾页
    prve = '<li><a href="?page={}">尾页</a></li>'.format(total_page_count)
    tpl_str_list.append(prve)

    page_string = mark_safe("".join(tpl_str_list))

    queryset = Depart.objects.filter(**data_dict)[start:end]

    return render(request,"carcer_list.html",{"queryset":queryset,"search_data":search_data,"page_string":page_string})

from app01.utils.bootstraps import Bootstrap

class CarcerModelForm(Bootstrap):
    class Meta:
        model=Depart
        fields="__all__"

def carcer_add(request):
    '''添加职务'''
    title="添加职务"
    if request.method=="GET":
        form=CarcerModelForm()
        return render(request,"change.html",{"form":form,"title":title})
    form=CarcerModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/carcer/list/")
    return render(request,"change.htmll",{"form":form})

def carcer_delete(request,id):
    '''删除职务'''
    Depart.objects.filter(id=id).first()
    return render(request,"carcer_list.html")

def carcer_edit(request,id):
    '''编辑职务'''
    data=Depart.objects.filter(id=id).first()
    if request.method=="GET":
        form=CarcerModelForm(instance=data)
        return render(request,"change.html",{"form":form})
    form=CarcerModelForm(data=request.POST,instance=data)
    if form.is_valid():
        form.save()
        return redirect("/carcer/list/")
    return render(request,"change.html",{"form":form})

app01/views/chart.py
from  django.shortcuts import render
from django.http import JsonResponse

def chart_list(request):
    '''数据显示'''
    return render(request,"chart_list.html")

app01/views/hotel.py
from django.shortcuts import redirect,render
from django.utils.safestring import mark_safe

from app01.models import Hotel

def hotel_list(request):
    '''酒席展示'''
    data_dict={}
    search_data=request.GET.get('q',"")
    if search_data:
        data_dict["wine__contains"]=search_data


    page = int(request.GET.get("page", "1"))   # 当前页
    page_size = 10  # 每页显示10条数据
    start = (page - 1) * 10
    end = page * 10
    total_count = Hotel.objects.filter(**data_dict).order_by("-id").count() # 数据总条数

    # 计算总页码
    total_page_count,div = divmod(total_count,page_size)
    if div>1:   #余数大于1
        total_page_count += 1

    # 分页第二步
    # 计算出,显示当前页的前5页,后5页
    plus = 5



    if total_page_count < 2 * plus + 1:
        # 当数据库的数据库比较少的时候,都没有达到11页
        start_page = 1
        end_page = total_page_count
    else:
        # 当前页小于5时
        if page <= plus:
            start_page = 1
            end_page = 2 * plus + 1
        # 当数据库的数据库比较多的时候
        else:
            # 当前页大于5时
            if page + plus > total_page_count:
                start_page = total_page_count - 2 * plus   #往前推10个
                end_page = total_page_count
            else:
                start_page = page - plus
                end_page = page + plus + 1


    tpl_str_list = []

    # 首页
    prve = '<li><a href="?page={}">首页</a></li>'.format(1)
    tpl_str_list.append(prve)

    # 上一页
    if page >1:
        prve = '<li><a href="?page={}">上一页</a></li>'.format(page-1)
    else:
        prve = '<li><a href="?page={}">上一页</a></li>'.format(1)
    tpl_str_list.append(prve)



    for i in range(start_page, end_page+1):
        if i == page:
            ele = '<li class="active"><a href="?page={}">{}</a></li>'.format(i, i)
        else:
            ele = '<li><a href="?page={}">{}</a></li>'.format(i, i)
        tpl_str_list.append(ele)

    # 下一页
    if page < total_page_count:
        prve = '<li><a href="?page={}">下一页</a></li>'.format(page + 1)
    else:
        prve = '<li><a href="?page={}">下一页</a></li>'.format(total_page_count)
    tpl_str_list.append(prve)

    # 尾页
    prve = '<li><a href="?page={}">尾页</a></li>'.format(total_page_count)
    tpl_str_list.append(prve)

    page_string = mark_safe("".join(tpl_str_list))

    queryset=Hotel.objects.filter(**data_dict)[start:end]
    return render(request,"hotel_list.html",{"queryset":queryset,"search_data":search_data,"page_string":page_string})


from app01.utils.bootstraps import Bootstrap
class HotelModelForm(Bootstrap):
    class Meta:
        model=Hotel
        fields="__all__"

def hotel_add(request):
    '''添加酒席'''
    title="添加酒席"
    if request.method=="GET":
        form=HotelModelForm()
        return render(request,"change.html",{"form":form,"title":title})
    form=HotelModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/hotel/list/")
    return render(request,"change.html",{"form":form})


def hotel_edit(request,id):
    '''编辑酒席'''
    data=Hotel.objects.filter(id=id).first()
    if request.method=="GET":
        form=HotelModelForm(instance=data)
        return render(request,"change.html",{"form":form})
    form=HotelModelForm(data=request.POST,instance=data)
    if form.is_valid():
        form.save()
        return redirect("/hotel/list/")
    return render(request,"change.html",{"form":form})

def hotel_delete(request,id):
    '''删除酒席'''
    Hotel.objects.filter(id=id).first()
    return redirect("/hotel/list/")

app01/views/info.py
from django.shortcuts import redirect,render,HttpResponse
from app01.models import Admin


def info_list(request):
    '''现实个人信息'''
    return render(request,"info_list.html")

def register(request):
    '''注册管理员'''
    if request.method=="GET":
        return render(request,"register.html")

    name=request.POST.get("name")
    password=request.POST.get("password")
    Admin.objects.create(adminname=name,password=password)
    return redirect("/login/")

app01/templates/error.html
{% extends 'layout.html' %}

{% block content %}
    <h1 style="color: red">用户名或者密码错误!</h1>

{% endblock %}

app01/templates/hotel_list.html
{% extends 'layout.html' %}



{% block content %}

    {#搜索框#}


    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">婚庆酒席表</div>
            <div class="panel-body">
                <a href="/hotel/add/" class="btn btn-success">添加酒桌</a>
                <div style="float: right;width: 200px">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="请输入酒的类型"
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">桌数量</th>
                    <th scope="col">酒类</th>
                    <th scope="col">价格</th>
                    <th scope="col">类型</th>
                    <th scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for foo in queryset %}
                    <tr>
                        <td>{{ foo.id }}</td>
                        <td>{{ foo.num }}</td>
                        <td>{{ foo.wine }}</td>
                        <td>{{ foo.price}}</td>
                        <td>{{ foo.get_wine_type_display}}</td>
                        <td>
                            <a href="/hotel/{{ foo.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                            <a href="/hotel/{{ foo.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>


    <div class="clearfix" style="margin-left: 520px">
        <ul class="pagination" style="float: left">
            {{ page_string }}
            <li>
                <form method="get" style="float: left;margin-left: -1px">
                    <div class="input-group" style="width: 120px">
                        <input type="text" class="form-control" name="page" placeholder="页码" value="" required
                               style="position:relative;float: left;display: inline-block;width: 80px;border-radius: 0;">
                        <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">跳转</button>
                                </span>
                    </div>
                </form>
            </li>
        </ul>
    </div>


    </div>
{% endblock %}

app01/templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
   <head>
      <meta charset="UTF-8">
      <title></title>

        <link rel="stylesheet" href="{% static 'plugins/bootstrap-3.4.1-dist/css/bootstrap.css' %}">
      <style>
         .account{
             background: #ffffff;
            width: 400px;
             height: 600px;
            border: 1px solid #dddddd;
            border-radius: 5px;
            box-shadow: 5px 5px 20px #aaa;

            margin-left: 50px;
            margin-right: auto;
            margin-top: 100px;
            padding: 20px 40px;
         }
         .account h2{
            margin-top: 10px;
            text-align: center;
         }
         body {
             background: #fff url({% static 'img/home.jpg' %}) no-repeat left top;
             background-size: 100%;
         }

      </style>

   </head>

   <body>

   <div class="account">
       <h2>用户登录</h2>
       <form method="post" novalidate>
           {% csrf_token %}
           <div class="form-group">
               <label>用户名</label>
               {{ form.adminname }}
               <span style="color: red">{{ form.adminname.errors.0 }}</span>
           </div>
           <div class="form-group">
               <label>密码</label>
               {{ form.password }}
               <span style="color: red">{{ form.password.errors.0 }}</span>
           </div>

           <div class="form-group">
               <label for="id_code">图片验证码</label>
               <div class="row">
                   <div class="col-xs-7">
                       {{ form.code }}
                       <span style="color: red;">{{ form.password.errors.0 }}</span>
                   </div>
                   <div class="col-xs-5">
                       <img id="image_code" src="/image/code/">
                   </div>
               </div>
           </div>
           <input type="submit" value="登  录" class="btn btn-lg btn-primary" style="width: 330px;margin-top: 30px"/>

           <a href="/register">
               <span class="btn btn-default" style="margin-top: 15px;width: 330px;line-height: 30px">注册</span>
           </a>

       </form>
   </div>


   </body>
</html>

app01/templates/order.html
{% extends 'layout.html' %}

{% block content %}


{#    显示数据#}
    <div class="container">


        <div class="panel panel-default">
        <div class="panel-heading">订单表</div>
        <div class="panel-body">
             <button id="orderAdd" class="btn btn-primary">新建订单</button>
        </div>
    </div>
            <table class="table table-bordered table-striped">
                <thead>
                <tr>
                    <th scope="col">订单号</th>
                    <th scope="col">姓名</th>
                    <th scope="col">婚礼日期</th>
                    <th scope="col">婚礼地址</th>
                    <th scope="col">联系电话</th>
                    <th scope="col">支付状态</th>
                    <th scope="col">级别</th>
                    <th scope="col">操作</th>
                </tr>
                </thead>
                <tbody>
                {% for foo in queryset %}
                    <tr>
                        <td>{{ foo.oid }}</td>
                        <td>{{ foo.name }}</td>
                        <td>{{ foo.datatime}}</td>
                        <td>{{ foo.address }}</td>
                        <td>{{ foo.phone}}</td>
                        <td>{{ foo.get_status_choice_display }}</td>
                        <td>{{ foo.get_level_choice_display }}</td>
                        <td>
{#                            <input nid="{{ foo.id }}" class="btn btn-primary btn-xs btn-edit" type="button" value="编辑">#}
                            <input nid="{{ foo.id }}" class="btn btn-danger btn-xs btn-delete" value="删除" type="button">
                        </td>
                    </tr>
                {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

{#    弹出新建框#}
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span
                            aria-hidden="true">&times;</span></button>
                    <h4 class="modal-title" id="myModalLabel">新建订单</h4>
                </div>
                <div class="modal-body">
                    <form id="addFrom" novalidate>
                        <div class="clearfix">
                            {% for item in form %}
                                <div class="col-xs-12">
                                    <div class="form-group" style="position: relative">
                                        <label>{{ item.label }}</label>
                                        {{ item }}
                                        <span class="error_msg" style="color: red;position: absolute"></span>
                                    </div>
                                </div>
                            {% endfor %}
                        </div>
                    </form>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button id="btnSave" type="button" class="btn btn-primary">保存</button>
                </div>
            </div>
        </div>
    </div>


{#    删除框#}
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">

            <div class="alert alert-danger" role="alert">
                    <div class="modal-header">
                        <h4 class="modal-title" id="myModalLabel">确认是否删除？</h4>
                    </div>
                    <div class="modal-body">
                        删除后，关联数据都会被删除
                    </div>
                    <button type="button" class="btn btn-default" data-dismiss="modal">取消</button>
                    <button type="button" class="btn btn-danger" id="btnConfire">确定</button>
                </div>
            </div>
        </div>
    </div>

{% endblock %}



{% block js %}
    <script type="application/javascript">
    var DELETE_ID;
    $(function () {
        bindBtnAddEvent();
        bindBtnSaveEvent();
        bindBtnDeleteEvent();
        bindBtnConfireEvent();
    })

    function bindBtnAddEvent() {
        $("#orderAdd").click(function () {
            $("#myModal").modal("show");
        });
    }
    function bindBtnSaveEvent() {
        $("#btnSave").click(function () {
            {#清除错误信息#}
            $("#error_msg").empty()
            {#向后台发送数据#}
            $.ajax({
                url: "/order/add/",
                type: "post",
                data: $("#addFrom").serialize(),
                dataType: "JSON",
                success: function (res) {
                    if (res.status) {
                        {#    清空表单错误信息#}
                        $("#addFrom")[0].reset();
                        {#隐藏表单#}
                        $("#myModal").modal("hide");
                        {#    自动刷新显示数据#}
                        location.reload();
                    } else {
                        $.each(res.error, function (name, errorList) {
                            $("#id_" + name).next().text(errorList)[0]
                        })
                    }
                }
            })
        });
    }

    function bindBtnDeleteEvent() {
        $(".btn-delete").click(function () {
            $("#deleteModal").modal("show");
            DELETE_ID=$(this).attr("nid");
        })
    }

    function bindBtnConfireEvent() {
        $("#btnConfire").click(function () {
            $.ajax({
                url:"/order/delete/",
                type: "get",
                data:{
                    nid:DELETE_ID
                },
                dataType: "JSON",
                success:function (res) {
                    if (res.status){
                        location.reload();
                    }
                    else{
                        alert(res.error)
                    }

                }
            })

        })

    }

    </script>

{% endblock %}

app01/templates/service_list.html
{% extends 'layout.html' %}

{% block content %}

    {#搜索框#}


    <div class="container">
        <div class="panel panel-default">
            <div class="panel-heading">婚车表</div>
            <div class="panel-body">
                <a href="/service/add/" class="btn btn-success">添加婚车</a>
                <div style="float: right;width: 200px">
                    <form method="get">
                        <div class="input-group">
                            <input type="text" name="q" class="form-control" placeholder="请输入车的品牌"
                                   value="{{ search_data }}">
                            <span class="input-group-btn">
                <button class="btn btn-default" type="submit">
                    <span class="glyphicon glyphicon-search" aria-hidden="true"></span>
                </button>
            </span>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <table class="table table-bordered table-striped">
            <thead>
            <tr>
                <th scope="col">ID</th>
                <th scope="col">数量</th>
                <th scope="col">品牌</th>
                <th scope="col">价格</th>
                <th scope="col">状态</th>
                <th scope="col">颜色</th>
                <th scope="col">操作</th>
            </tr>
            </thead>
            <tbody>
            {% for foo in queryset %}
                <tr>
                    <td>{{ foo.id }}</td>
                    <td>{{ foo.num }}</td>
                    <td>{{ foo.typeCar }}</td>
                    <td>{{ foo.price }}</td>
                    <td>{{ foo.get_status_choice_display }}</td>
                    <td>{{ foo.colour }}</td>
                    <td>
                        <a href="/service/{{ foo.id }}/edit/" class="btn btn-primary btn-xs">编辑</a>
                        <a href="/service/{{ foo.id }}/delete/" class="btn btn-danger btn-xs">删除</a>
                    </td>
                </tr>
            {% endfor %}
            </tbody>
        </table>

        <div class="clearfix" style="margin-left: 520px">
        <ul class="pagination" style="float: left">
            {{ page_string }}
            <li>
                <form method="get" style="float: left;margin-left: -1px">
                    <div class="input-group" style="width: 120px">
                        <input type="text" class="form-control" name="page" placeholder="页码" value="" required
                               style="position:relative;float: left;display: inline-block;width: 80px;border-radius: 0;">
                        <span class="input-group-btn">
                                    <button class="btn btn-default" type="submit">跳转</button>
                                </span>
                    </div>
                </form>
            </li>
        </ul>
    </div>
    </div>
    </div>
{% endblock %}